services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
    - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWD}
      - PGDATA=/data/postgres-monopoly
    volumes:
      - ./docker/*.sql /docker-entrypoint-initdb.d/
      - ./docker/docker-database/:/data/postgres-monopoly
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
    - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWD}
    volumes:
       - ./docker/docker-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"